"""initial secure schema

Revision ID: 20260918_01
Revises: 
Create Date: 2026-09-18 11:58:08.831503
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '20260918_01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

ENUMS = {
    'role': ('FISCAL', 'SUPERVISOR', 'ANALISTA', 'COORDENACAO', 'ADMINISTRADOR'),
    'checkliststatus': ('RASCUNHO', 'EM_REVISAO', 'PUBLICADO', 'ARQUIVADO'),
    'inspectionstatus': ('RASCUNHO', 'CONCLUIDA'),
    'answerstatus': ('CONFORME', 'NAO_CONFORME', 'NAO_APLICA'),
    'severity': ('BAIXA', 'MEDIA', 'ALTA', 'CRITICA'),
    'occurrencestatus': ('ABERTA', 'EM_VALIDACAO', 'VALIDADA', 'REJEITADA', 'EM_TRATAMENTO', 'RESOLVIDA'),
}


def enum_type(name: str) -> sa.Enum:
    values = ENUMS[name]
    if op.get_bind().dialect.name == 'postgresql':
        return postgresql.ENUM(*values, name=name, create_type=False)
    return sa.Enum(*values, name=name)


def upgrade() -> None:
    if op.get_bind().dialect.name == 'postgresql':
        for name, values in ENUMS.items():
            postgresql.ENUM(*values, name=name).create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_throttles',
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('window_started_at', sa.DateTime(), nullable=False),
    sa.Column('blocked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key_hash')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('company', sa.String(length=160), nullable=False),
    sa.Column('last_inspection', sa.Date(), nullable=True),
    sa.Column('next_inspection', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_equipment_next_inspection'), 'equipment', ['next_inspection'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', enum_type('role'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=False),
    sa.Column('mfa_secret_encrypted', sa.String(length=500), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'entity', name='uq_audit_identity')
    )
    op.create_table('auth_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('details', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_events_actor_id'), 'auth_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_auth_events_created_at'), 'auth_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_auth_events_event_type'), 'auth_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_auth_events_outcome'), 'auth_events', ['outcome'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_expires_at'), 'auth_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('checklist_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('inspection_type', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', enum_type('checkliststatus'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_templates_inspection_type'), 'checklist_templates', ['inspection_type'], unique=False)
    op.create_index(op.f('ix_checklist_templates_status'), 'checklist_templates', ['status'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=40), nullable=False),
    sa.Column('inspection_type', sa.String(length=40), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('apron', sa.String(length=60), nullable=False),
    sa.Column('grid_cell', sa.String(length=12), nullable=True),
    sa.Column('location_text', sa.String(length=180), nullable=True),
    sa.Column('shift', sa.String(length=30), nullable=False),
    sa.Column('weather', sa.String(length=60), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', enum_type('inspectionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_protocol'), 'inspections', ['protocol'], unique=True)
    op.create_table('checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('item_key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=180), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('observation_required', sa.Boolean(), nullable=False),
    sa.Column('severity_required', sa.Boolean(), nullable=False),
    sa.Column('location_required', sa.Boolean(), nullable=False),
    sa.Column('evidence_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_items_template_id'), 'checklist_items', ['template_id'], unique=False)
    op.create_table('inspection_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('item_key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=180), nullable=False),
    sa.Column('status', enum_type('answerstatus'), nullable=False),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('severity', enum_type('severity'), nullable=True),
    sa.Column('evidence_url', sa.String(length=500), nullable=True),
    sa.Column('grid_cell', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('occurrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('grid_cell', sa.String(length=12), nullable=False),
    sa.Column('severity', enum_type('severity'), nullable=False),
    sa.Column('status', enum_type('occurrencestatus'), nullable=False),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['inspection_answers.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occurrences_inspection_id'), 'occurrences', ['inspection_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurrence_id', sa.Integer(), nullable=True),
    sa.Column('inspection_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['occurrence_id'], ['occurrences.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    if op.get_bind().dialect.name == 'postgresql':
        public_roles = op.get_bind().execute(sa.text(
            "SELECT rolname FROM pg_roles WHERE rolname IN ('anon', 'authenticated')"
        )).scalars().all()
        for table in (
            'auth_throttles', 'equipment', 'users', 'audit_logs', 'auth_events', 'auth_sessions',
            'checklist_templates', 'inspections', 'checklist_items', 'inspection_answers',
            'occurrences', 'attachments', 'alembic_version',
        ):
            op.execute(sa.text(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY'))
            for role in public_roles:
                op.execute(sa.text(f'REVOKE ALL PRIVILEGES ON TABLE "{table}" FROM "{role}"'))
        for role in public_roles:
            op.execute(sa.text(f'REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM "{role}"'))
            op.execute(sa.text(f'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM "{role}"'))
            op.execute(sa.text(f'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM "{role}"'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    op.drop_index(op.f('ix_occurrences_inspection_id'), table_name='occurrences')
    op.drop_table('occurrences')
    op.drop_table('inspection_answers')
    op.drop_index(op.f('ix_checklist_items_template_id'), table_name='checklist_items')
    op.drop_table('checklist_items')
    op.drop_index(op.f('ix_inspections_protocol'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_checklist_templates_status'), table_name='checklist_templates')
    op.drop_index(op.f('ix_checklist_templates_inspection_type'), table_name='checklist_templates')
    op.drop_table('checklist_templates')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_expires_at'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_auth_events_outcome'), table_name='auth_events')
    op.drop_index(op.f('ix_auth_events_event_type'), table_name='auth_events')
    op.drop_index(op.f('ix_auth_events_created_at'), table_name='auth_events')
    op.drop_index(op.f('ix_auth_events_actor_id'), table_name='auth_events')
    op.drop_table('auth_events')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_equipment_next_inspection'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_table('auth_throttles')
    if op.get_bind().dialect.name == 'postgresql':
        for name, values in reversed(tuple(ENUMS.items())):
            postgresql.ENUM(*values, name=name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
